# Generated by Django 4.2.6 on 2023-12-01 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ablog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog", options={"ordering": ["-publish_date"]},
        ),
        migrations.AlterModelOptions(
            name="comment", options={"ordering": ("-comment_date",)},
        ),
    ]
